// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package customer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message để tạo một customer mới.
type CustomerRequest struct {
	Id                   int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*CustomerRequest_Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CustomerRequest) Reset()         { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()    {}
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}

func (m *CustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest.Unmarshal(m, b)
}
func (m *CustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest.Marshal(b, m, deterministic)
}
func (m *CustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest.Merge(m, src)
}
func (m *CustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest.Size(m)
}
func (m *CustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest proto.InternalMessageInfo

func (m *CustomerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRequest) GetAddresses() []*CustomerRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CustomerRequest_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	IsShippingAddress    bool     `protobuf:"varint,5,opt,name=isShippingAddress,proto3" json:"isShippingAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerRequest_Address) Reset()         { *m = CustomerRequest_Address{} }
func (m *CustomerRequest_Address) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest_Address) ProtoMessage()    {}
func (*CustomerRequest_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0, 0}
}

func (m *CustomerRequest_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest_Address.Unmarshal(m, b)
}
func (m *CustomerRequest_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest_Address.Marshal(b, m, deterministic)
}
func (m *CustomerRequest_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest_Address.Merge(m, src)
}
func (m *CustomerRequest_Address) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest_Address.Size(m)
}
func (m *CustomerRequest_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest_Address.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest_Address proto.InternalMessageInfo

func (m *CustomerRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CustomerRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CustomerRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CustomerRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *CustomerRequest_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type CustomerResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerResponse) Reset()         { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()    {}
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}

func (m *CustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerResponse.Unmarshal(m, b)
}
func (m *CustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerResponse.Marshal(b, m, deterministic)
}
func (m *CustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerResponse.Merge(m, src)
}
func (m *CustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerResponse.Size(m)
}
func (m *CustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerResponse proto.InternalMessageInfo

func (m *CustomerResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CustomerFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerFilter) Reset()         { *m = CustomerFilter{} }
func (m *CustomerFilter) String() string { return proto.CompactTextString(m) }
func (*CustomerFilter) ProtoMessage()    {}
func (*CustomerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{2}
}

func (m *CustomerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerFilter.Unmarshal(m, b)
}
func (m *CustomerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerFilter.Marshal(b, m, deterministic)
}
func (m *CustomerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerFilter.Merge(m, src)
}
func (m *CustomerFilter) XXX_Size() int {
	return xxx_messageInfo_CustomerFilter.Size(m)
}
func (m *CustomerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerFilter proto.InternalMessageInfo

func (m *CustomerFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerRequest)(nil), "customer.CustomerRequest")
	proto.RegisterType((*CustomerRequest_Address)(nil), "customer.CustomerRequest.Address")
	proto.RegisterType((*CustomerResponse)(nil), "customer.CustomerResponse")
	proto.RegisterType((*CustomerFilter)(nil), "customer.CustomerFilter")
}

func init() {
	proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46)
}

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x4a, 0xeb, 0x40,
	0x10, 0xc6, 0xbb, 0x69, 0xd3, 0x3f, 0x73, 0x0e, 0x39, 0xed, 0x50, 0x0e, 0x7b, 0x72, 0x95, 0x93,
	0xab, 0x20, 0x52, 0x4a, 0xbd, 0x15, 0x44, 0x0a, 0x16, 0x2f, 0x14, 0x8c, 0x4f, 0x10, 0x93, 0xc1,
	0x2e, 0xb6, 0x49, 0xcc, 0x6e, 0x90, 0xfa, 0x0a, 0xbe, 0x8c, 0xaf, 0xe0, 0x9b, 0x49, 0x36, 0xd9,
	0x16, 0x5a, 0x7b, 0xd3, 0xbb, 0xf9, 0xbe, 0x99, 0xfd, 0xe6, 0x97, 0x21, 0xe0, 0xc4, 0xa5, 0x54,
	0xd9, 0x9a, 0x8a, 0x49, 0x5e, 0x64, 0x2a, 0xc3, 0xbe, 0xd1, 0xfe, 0xa7, 0x05, 0x7f, 0xe6, 0x8d,
	0x08, 0xe9, 0xb5, 0x24, 0xa9, 0xd0, 0x01, 0x4b, 0x24, 0x9c, 0x79, 0x2c, 0xb0, 0x43, 0x4b, 0x24,
	0x88, 0xd0, 0x49, 0xa3, 0x35, 0x71, 0xcb, 0x63, 0xc1, 0x20, 0xd4, 0x35, 0x8e, 0xc1, 0xa6, 0x75,
	0x24, 0x56, 0xbc, 0xad, 0xcd, 0x5a, 0x54, 0x6e, 0xbe, 0xcc, 0x52, 0xe2, 0x9d, 0xda, 0xd5, 0x02,
	0xaf, 0x60, 0x10, 0x25, 0x49, 0x41, 0x52, 0x92, 0xe4, 0xb6, 0xd7, 0x0e, 0x7e, 0xcd, 0xfe, 0x4f,
	0xb6, 0x44, 0x7b, 0xdb, 0x27, 0xd7, 0xf5, 0x68, 0xb8, 0x7b, 0xe3, 0x7e, 0x30, 0xe8, 0x35, 0x36,
	0xfe, 0x85, 0xae, 0x54, 0x05, 0x91, 0xd2, 0x80, 0x83, 0xb0, 0x51, 0x15, 0x64, 0x2c, 0xd4, 0xc6,
	0x40, 0x56, 0x75, 0x85, 0x23, 0x55, 0xa4, 0xc8, 0x40, 0x6a, 0x81, 0x43, 0x68, 0xbf, 0x8b, 0xbc,
	0x41, 0xac, 0x4a, 0x3c, 0x87, 0x91, 0x90, 0x8f, 0x4b, 0x91, 0xe7, 0x22, 0x7d, 0x6e, 0x16, 0x71,
	0xdb, 0x63, 0x41, 0x3f, 0x3c, 0x6c, 0xf8, 0x97, 0x30, 0xdc, 0x31, 0xcb, 0x3c, 0x4b, 0x25, 0x1d,
	0x9c, 0x8c, 0x43, 0x4f, 0x96, 0x71, 0x5c, 0xe5, 0x58, 0x3a, 0xc7, 0x48, 0xff, 0x0c, 0x1c, 0xf3,
	0xfa, 0x46, 0xac, 0x14, 0x15, 0xd5, 0xec, 0x0b, 0x6d, 0xde, 0xb2, 0x22, 0x69, 0x3e, 0xc9, 0xc8,
	0xd9, 0x97, 0x05, 0x7d, 0x33, 0x8c, 0xb7, 0xe0, 0xcc, 0x0b, 0x8a, 0x14, 0x6d, 0x9d, 0x7f, 0x47,
	0x8f, 0xe8, 0xba, 0x3f, 0xb5, 0x6a, 0x56, 0xbf, 0x85, 0x0b, 0xf8, 0xbd, 0x20, 0x65, 0x1a, 0x12,
	0xf9, 0xe1, 0x74, 0xcd, 0xe6, 0x1e, 0x5f, 0xe1, 0xb7, 0xa6, 0x0c, 0x1f, 0x60, 0x5c, 0x33, 0xdd,
	0x95, 0x2b, 0x25, 0x76, 0x81, 0xa7, 0x92, 0x05, 0x0c, 0xef, 0x61, 0xb4, 0x20, 0xb5, 0x97, 0x77,
	0x1a, 0x60, 0xc0, 0xa6, 0xec, 0xa9, 0xab, 0xff, 0xf8, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x57, 0x43, 0x77, 0x46, 0x03, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	// Tạo một customer: Unary methods
	CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error)
	// Get customer theo CustomerFilter: A server-to-client streaming RPC.
	GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (Customer_GetCustomersClient, error)
	// Create multi customer: A client-to-server streaming RPC.
	CreateMultiCustomers(ctx context.Context, opts ...grpc.CallOption) (Customer_CreateMultiCustomersClient, error)
	// Get multi customer  A Bidirectional streaming RPC.
	GetMultiCustomers(ctx context.Context, opts ...grpc.CallOption) (Customer_GetMultiCustomersClient, error)
}

type customerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerClient(cc grpc.ClientConnInterface) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerResponse, error) {
	out := new(CustomerResponse)
	err := c.cc.Invoke(ctx, "/customer.Customer/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomers(ctx context.Context, in *CustomerFilter, opts ...grpc.CallOption) (Customer_GetCustomersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[0], "/customer.Customer/GetCustomers", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerGetCustomersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Customer_GetCustomersClient interface {
	Recv() (*CustomerRequest, error)
	grpc.ClientStream
}

type customerGetCustomersClient struct {
	grpc.ClientStream
}

func (x *customerGetCustomersClient) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customerClient) CreateMultiCustomers(ctx context.Context, opts ...grpc.CallOption) (Customer_CreateMultiCustomersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[1], "/customer.Customer/CreateMultiCustomers", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerCreateMultiCustomersClient{stream}
	return x, nil
}

type Customer_CreateMultiCustomersClient interface {
	Send(*CustomerRequest) error
	CloseAndRecv() (*CustomerResponse, error)
	grpc.ClientStream
}

type customerCreateMultiCustomersClient struct {
	grpc.ClientStream
}

func (x *customerCreateMultiCustomersClient) Send(m *CustomerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *customerCreateMultiCustomersClient) CloseAndRecv() (*CustomerResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CustomerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customerClient) GetMultiCustomers(ctx context.Context, opts ...grpc.CallOption) (Customer_GetMultiCustomersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Customer_serviceDesc.Streams[2], "/customer.Customer/GetMultiCustomers", opts...)
	if err != nil {
		return nil, err
	}
	x := &customerGetMultiCustomersClient{stream}
	return x, nil
}

type Customer_GetMultiCustomersClient interface {
	Send(*CustomerFilter) error
	Recv() (*CustomerRequest, error)
	grpc.ClientStream
}

type customerGetMultiCustomersClient struct {
	grpc.ClientStream
}

func (x *customerGetMultiCustomersClient) Send(m *CustomerFilter) error {
	return x.ClientStream.SendMsg(m)
}

func (x *customerGetMultiCustomersClient) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	// Tạo một customer: Unary methods
	CreateCustomer(context.Context, *CustomerRequest) (*CustomerResponse, error)
	// Get customer theo CustomerFilter: A server-to-client streaming RPC.
	GetCustomers(*CustomerFilter, Customer_GetCustomersServer) error
	// Create multi customer: A client-to-server streaming RPC.
	CreateMultiCustomers(Customer_CreateMultiCustomersServer) error
	// Get multi customer  A Bidirectional streaming RPC.
	GetMultiCustomers(Customer_GetMultiCustomersServer) error
}

// UnimplementedCustomerServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func (*UnimplementedCustomerServer) CreateCustomer(ctx context.Context, req *CustomerRequest) (*CustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (*UnimplementedCustomerServer) GetCustomers(req *CustomerFilter, srv Customer_GetCustomersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCustomers not implemented")
}
func (*UnimplementedCustomerServer) CreateMultiCustomers(srv Customer_CreateMultiCustomersServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateMultiCustomers not implemented")
}
func (*UnimplementedCustomerServer) GetMultiCustomers(srv Customer_GetMultiCustomersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMultiCustomers not implemented")
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Customer/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreateCustomer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomerFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CustomerServer).GetCustomers(m, &customerGetCustomersServer{stream})
}

type Customer_GetCustomersServer interface {
	Send(*CustomerRequest) error
	grpc.ServerStream
}

type customerGetCustomersServer struct {
	grpc.ServerStream
}

func (x *customerGetCustomersServer) Send(m *CustomerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Customer_CreateMultiCustomers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CustomerServer).CreateMultiCustomers(&customerCreateMultiCustomersServer{stream})
}

type Customer_CreateMultiCustomersServer interface {
	SendAndClose(*CustomerResponse) error
	Recv() (*CustomerRequest, error)
	grpc.ServerStream
}

type customerCreateMultiCustomersServer struct {
	grpc.ServerStream
}

func (x *customerCreateMultiCustomersServer) SendAndClose(m *CustomerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *customerCreateMultiCustomersServer) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Customer_GetMultiCustomers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CustomerServer).GetMultiCustomers(&customerGetMultiCustomersServer{stream})
}

type Customer_GetMultiCustomersServer interface {
	Send(*CustomerRequest) error
	Recv() (*CustomerFilter, error)
	grpc.ServerStream
}

type customerGetMultiCustomersServer struct {
	grpc.ServerStream
}

func (x *customerGetMultiCustomersServer) Send(m *CustomerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *customerGetMultiCustomersServer) Recv() (*CustomerFilter, error) {
	m := new(CustomerFilter)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _Customer_CreateCustomer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCustomers",
			Handler:       _Customer_GetCustomers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateMultiCustomers",
			Handler:       _Customer_CreateMultiCustomers_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMultiCustomers",
			Handler:       _Customer_GetMultiCustomers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "customer.proto",
}
